"""Memory system: ontology engine, memory manager, versioning."""

from .manager import (
    ConversationSession,
    ConversationTurn,
    MemoryItem,
    MemoryManager,
    MemoryManagerConfig,
    MemoryPriority,
    MemoryStats,
    MemoryStatus,
    MemoryType,
    SearchResult,
)
from .ontology import (
    Concept,
    EntityType,
    GraphEdge,
    GraphNode,
    Individual,
    InferenceRule,
    OntologyConfig,
    OntologyEngine,
    PropertyDefinition,
    QueryResult,
    RelationDefinition,
    RelationInstance,
    RelationType,
    SubGraph,
)
from .versioning import (
    ConflictInfo,
    ConflictResolver,
    ConflictStatus,
    ConflictType,
    CredibilitySource,
    MemoryVersion,
    Resolution,
    ResolutionStrategy,
    VersionedMemory,
)

__all__ = [
    # Memory Manager
    "ConversationSession",
    "ConversationTurn",
    "MemoryItem",
    "MemoryManager",
    "MemoryManagerConfig",
    "MemoryPriority",
    "MemoryStats",
    "MemoryStatus",
    "MemoryType",
    "SearchResult",
    # Ontology Engine
    "Concept",
    "EntityType",
    "GraphEdge",
    "GraphNode",
    "Individual",
    "InferenceRule",
    "OntologyConfig",
    "OntologyEngine",
    "PropertyDefinition",
    "QueryResult",
    "RelationDefinition",
    "RelationInstance",
    "RelationType",
    "SubGraph",
    # Versioning & Conflict Resolution
    "ConflictInfo",
    "ConflictResolver",
    "ConflictStatus",
    "ConflictType",
    "CredibilitySource",
    "MemoryVersion",
    "Resolution",
    "ResolutionStrategy",
    "VersionedMemory",
]
