"""Memory system: ontology engine, memory manager, versioning, cold start scanner."""

from .manager import (
    ConversationSession,
    ConversationTurn,
    MemoryItem,
    MemoryManager,
    MemoryManagerConfig,
    MemoryPriority,
    MemoryStats,
    MemoryStatus,
    MemoryType,
    SearchResult,
)
from .ontology import (
    Concept,
    EntityType,
    GraphEdge,
    GraphNode,
    Individual,
    InferenceRule,
    OntologyConfig,
    OntologyEngine,
    PropertyDefinition,
    QueryResult,
    RelationDefinition,
    RelationInstance,
    RelationType,
    SubGraph,
)
from .versioning import (
    ConflictInfo,
    ConflictResolver,
    ConflictStatus,
    ConflictType,
    CredibilitySource,
    MemoryVersion,
    Resolution,
    ResolutionStrategy,
    VersionedMemory,
)
from .cold_start import (
    ColdStartScanner,
    Dependency,
    DockerInfo,
    DockerService,
    FileTypeInfo,
    ProjectStructure,
    ScanResult,
    scan_and_populate,
)
from .multimodal import (
    CodeParser,
    CodeStructure,
    ContentModality,
    MultiModalMemory,
    ProcessedContent,
)
from .audit import (
    AuditFlag,
    AuditItem,
    AuditReport,
    AuditResult,
    CleanupAction,
    CleanupDetail,
    CleanupResult,
    MemoryAuditor,
    Severity,
)

__all__ = [
    # Memory Manager
    "ConversationSession",
    "ConversationTurn",
    "MemoryItem",
    "MemoryManager",
    "MemoryManagerConfig",
    "MemoryPriority",
    "MemoryStats",
    "MemoryStatus",
    "MemoryType",
    "SearchResult",
    # Ontology Engine
    "Concept",
    "EntityType",
    "GraphEdge",
    "GraphNode",
    "Individual",
    "InferenceRule",
    "OntologyConfig",
    "OntologyEngine",
    "PropertyDefinition",
    "QueryResult",
    "RelationDefinition",
    "RelationInstance",
    "RelationType",
    "SubGraph",
    # Versioning & Conflict Resolution
    "ConflictInfo",
    "ConflictResolver",
    "ConflictStatus",
    "ConflictType",
    "CredibilitySource",
    "MemoryVersion",
    "Resolution",
    "ResolutionStrategy",
    "VersionedMemory",
    # Cold Start Scanner
    "ColdStartScanner",
    "Dependency",
    "DockerInfo",
    "DockerService",
    "FileTypeInfo",
    "ProjectStructure",
    "ScanResult",
    "scan_and_populate",
    # Multi-Modal Memory
    "CodeParser",
    "CodeStructure",
    "ContentModality",
    "MultiModalMemory",
    "ProcessedContent",
    # Memory Audit
    "AuditFlag",
    "AuditItem",
    "AuditReport",
    "AuditResult",
    "CleanupAction",
    "CleanupDetail",
    "CleanupResult",
    "MemoryAuditor",
    "Severity",
]
