"""Core package public exports.

Exports are resolved lazily so importing ``symbio.core`` does not eagerly load
optional heavy dependencies such as LanceDB/PyArrow.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES: dict[str, str] = {
    "AlignmentResult": "cache_aligner",
    "AlignmentStrategy": "cache_aligner",
    "CacheAligner": "cache_aligner",
    "CacheAlignerConfig": "cache_aligner",
    "CacheProvider": "cache_aligner",
    "CacheableRequest": "cache_aligner",
    "HitRateEstimate": "cache_aligner",
    "PrefixGroup": "cache_aligner",
    "PrefixSegment": "cache_aligner",
    "DecompositionResult": "decomposer",
    "SubTask": "decomposer",
    "TaskDecomposer": "decomposer",
    "DAGOrchestrator": "dag_orchestrator",
    "DAGRuntime": "dag_runtime",
    "ExecutionArtifact": "execution_models",
    "ExecutionEvent": "execution_models",
    "ExecutionGraphVersion": "execution_models",
    "ExecutionNode": "execution_models",
    "ExecutionNodeStatus": "execution_models",
    "ExecutionPlan": "execution_models",
    "ExecutionPlanner": "execution_planner",
    "ExecutionRecord": "execution_models",
    "ExecutionStateStore": "execution_state_store",
    "ExecutionStatus": "execution_models",
    "ReplanDecision": "execution_models",
    "ReplanDecisionType": "execution_models",
    "Replanner": "replanner",
    "ResultReducer": "result_reducer",
    "ContextMessage": "context_pruner",
    "ContextPruner": "context_pruner",
    "DecisionKeyPoint": "context_pruner",
    "ImportanceLevel": "context_pruner",
    "MessageRole": "context_pruner",
    "PrunerConfig": "context_pruner",
    "PruneResult": "context_pruner",
    "PruneStrategy": "context_pruner",
    "StateDelta": "context_pruner",
    "DAGEngine": "dag_engine",
    "DAGNode": "dag_engine",
    "DAGStats": "dag_engine",
    "NodeObservation": "dag_engine",
    "NodeResult": "dag_engine",
    "NodeStatus": "dag_engine",
    "TopologyAction": "dag_engine",
    "TopologyChange": "dag_engine",
    "EventBus": "event_bus",
    "Event": "event_bus",
    "MemoryBridge": "memory_bridge",
    "get_memory_bridge": "memory_bridge",
    "AgentHandoff": "state_manager",
    "ErrorRecord": "state_manager",
    "FileInfo": "state_manager",
    "GlobalState": "state_manager",
    "InstructionGenerator": "state_manager",
    "PlannerReviewerLoop": "planner_reviewer",
    "PlannerReviewerResult": "planner_reviewer",
    "PlannerReviewerStatus": "planner_reviewer",
    "PlanStep": "planner_reviewer",
    "ReviewFinding": "planner_reviewer",
    "ReviewFindingSeverity": "planner_reviewer",
    "ReviewResult": "planner_reviewer",
    "StateManager": "state_manager",
    "TaskPhase": "state_manager",
    "TestResults": "state_manager",
    "AttackType": "injection_guard",
    "AuditRecord": "injection_guard",
    "DefenseLayer": "injection_guard",
    "DetectionResult": "injection_guard",
    "InjectionError": "injection_guard",
    "InjectionGuard": "injection_guard",
    "InjectionGuardConfig": "injection_guard",
    "SanitizeResult": "injection_guard",
    "ThreatLevel": "injection_guard",
    "AggregateStats": "resource_manager",
    "CircuitLevel": "resource_manager",
    "ResourceBudget": "resource_manager",
    "ResourceManager": "resource_manager",
    "ResourceStatusSnapshot": "resource_manager",
    "CacheEntry": "semantic_cache",
    "CacheStats": "semantic_cache",
    "InvalidationStrategy": "semantic_cache",
    "SemanticCacheConfig": "semantic_cache",
    "SemanticCacheEngine": "semantic_cache",
    "AgentCost": "cost_monitor",
    "BudgetManager": "cost_monitor",
    "BudgetStatus": "cost_monitor",
    "CacheKeepAlive": "cost_monitor",
    "CostSummary": "cost_monitor",
    "CostTracker": "cost_monitor",
    "ModelCost": "cost_monitor",
    "UsageRecord": "cost_monitor",
    "get_budget_manager": "cost_monitor",
    "get_cost_tracker": "cost_monitor",
    "shutdown_cost_monitor": "cost_monitor",
    "ExporterType": "tracer",
    "MetricType": "tracer",
    "MetricRecord": "tracer",
    "MemorySnapshot": "tracer",
    "SpanData": "tracer",
    "SpanEvent": "tracer",
    "TokenHeatmapEntry": "tracer",
    "TokenHeatmapSummary": "tracer",
    "TokenUsageSnapshot": "tracer",
    "TraceConfig": "tracer",
    "Tracer": "tracer",
    "get_tracer": "tracer",
    "init_tracer": "tracer",
    "shutdown_tracer": "tracer",
    "trace_agent": "tracer",
    "trace_tool": "tracer",
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module 'symbio.core' has no attribute {name!r}")
    module = import_module(f"{__name__}.{module_name}")
    value = getattr(module, name)
    globals()[name] = value
    return value
